### ISSUE TITLE
Bug - Sound Recorder Clicks

### ISSUE THREAD

**Issue by ghost** [ivanmeler/android_kernel_samsung_herolte#1]
When installed LineageOS on two phones (fresh install) I had problems recording sound with the native voice recorde, tried also other recorders and same issue

You can record, no problem, but when listening to the recordings you can hear sound clicks everywhere, except in silence. If you try to say "ahhhhhhhhhhhh" for 5 seconds for example, you will hear "clicks" over your recording. You can hear the "ahhhhhh" but with clicks over it.

Try to record anything with the magnetophone and listen, you will hear those "clicks".

**Comment by ghost** [comment]
So, regarding the Magnetophone or any other sound recorder problem, how to reproduce the issue: 

- Install a fresh LineageOS (I've wiped everything + formated)
- open Magnetophone app
- record your voice, sing a little bit, say "ahhhhhhh" or "ohhhhh" for 5 seconds
- listen to your recordings
- normally you will hear "clicks" over your voice or when there's any sound, nothing when there's silence.

And here's an example with a music I recorded for 1 minute: https://wetransfer.com/downloads/2ec3d0b7bb667eaa6b4e69983fd1dd9320200114162125/737439

It's not a phone problem, it works with a stock rom, and I tried on two phones, same issue.

**Comment by ivanmeler** [comment]
Resolved with 10.22.2020. build of LineageOS 17.1
